target-version = "py310"
line-length = 88
indent-width = 4
exclude = [
    ".venv",
    "__pycache__",
    ".egg-info"
]

[lint]
select = [
    "ANN", "B", "C4", "I", 
    "E", "W", "D", "F", 
    "PL" , "UP", "RUF"
]

ignore = [
    "D101", "D102", "D103", "D107",
    "D203", "D213", "ANN401",
]

[format]
quote-style = "single"
