name: certbot-dns-wedos
title: Certbot DNS Wedos
summary: Wedos DNS Authenticator plugin for Certbot
description: |
  This plugin uses the Certbot DNS-01 challenge to create and delete TXT
  records on the Wedos domain server using the Wedos API called the WAPI. 
  With this plugin, you can generate wildcard SSL certificates.
website: https://github.com/clazzor/certbot-dns-wedos
source-code: https://github.com/clazzor/certbot-dns-wedos
issues: https://github.com/clazzor/certbot-dns-wedos/issues
contact: https://github.com/clazzor
license: Apache-2.0
base: core24
grade: stable
confinement: strict
adopt-info: certbot-dns-wedos

parts:
  certbot-dns-wedos:
    plugin: python
    source: .
    override-pull: |
        craftctl default
        craftctl set version=$(grep ^version $CRAFT_PART_SRC/pyproject.toml | cut -f2 -d= | tr -d '"[:space:]')
    build-environment:
      - CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      - SNAP_BUILD: "True"
    build-packages:
      - gcc
      - git
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - cargo
      - pkg-config
  certbot-metadata:
    plugin: dump
    source: .
    stage: [pyproject.toml, certbot-shared]
    override-pull: |
        craftctl default
        mkdir -p $CRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
